name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Bypass husky pre-commit hook
        run: export HUSKY_SKIP_HOOKS=1

      - name: Generate and commit lock file
        run: |
          pnpm install
          git config --global user.email "jmbish04@gmail.com"
          git config --global user.name "Justin"
          git add pnpm-lock.yaml
          git commit -m "Generate pnpm lock file"
          git push

      - name: Install dependencies
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.13.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
