name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'  # Update to Node.js version 18.12.1 or higher

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm add -D webpack webpack-cli typescript ts-loader

      - name: Build project
        run: pnpm run build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          command: deploy examples/coagents-routing/ui/src/app/api/copilotkit/route.ts

      - name: Print wrangler command output
        env:
          CMD_OUTPUT: ${{ steps.deploy.outputs.command-output }}
        run: echo $CMD_OUTPUT
